# Generated by Django 3.2.25 on 2024-11-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_description_question_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='state',
            field=models.CharField(choices=[('répondu', 'Répondu'), ('pas encore répondu', 'Pas encore répondu')], default='pas encore répondu', max_length=255),
        ),
    ]
